language: node_js
node_js:
  - '12'

# Skip building branches unless except for master for automated releases
branches:
  only:
    - master

# Cache dependencies
cache: npm

# Default install is npm install w/ package.json
# install

# Default script is npm test
# script
